---
- name: Grafana | Cleanup old file-based provisioning
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ grafana_provisioning_dir }}/dashboards/dashboards.yaml"
    - "{{ grafana_provisioning_dir }}/dashboards_list"
  when: grafana_cleanup_old_provisioning | default(true) | bool

- name: Grafana | Create provisioning directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items:
    - "{{ grafana_provisioning_dir }}"
    - "{{ grafana_provisioning_dir }}/dashboards"
    - "{{ grafana_provisioning_dir }}/datasources"
    - "{{ grafana_provisioning_dir }}/repository"
    - "{{ grafana_provisioning_dir }}/notifiers"

- name: Grafana | Ensure datasources configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ grafana_provisioning_dir }}/datasources/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
  with_fileglob:
    - "../templates/datasources/*"

- name: Grafana | Ensure GitSync repository configuration file
  ansible.builtin.template:
    src: repository.yaml.j2
    dest: "{{ grafana_provisioning_dir }}/repository/repository.yaml"
    owner: root
    group: root
    mode: "0644"
  when: grafana_gitsync_enabled | default(true) | bool
