{
 "title": "Blockchain Nodes Mainnet",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_VICTORIAMETRICS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "BTC Mainnet / Reserve",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_block_number_diff{dns_hostname=\"hv_raw_btc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_local_block_number{dns_hostname=\"hv_raw_btc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_remote_block_number{dns_hostname=\"hv_raw_btc_mainnet\"}"
    }
   ]
  },
  { "title": "|", "type": "text", "gridPos": { "h": 3, "w": 1, "x": 9, "y": 1 }, "options": { "content": "\n" } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_block_number_diff{dns_hostname=\"hv_raw3_btc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_local_block_number{dns_hostname=\"hv_raw3_btc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_btc_mainnet_remote_block_number{dns_hostname=\"hv_raw3_btc_mainnet\"}"
    }
   ]
  },
  {
   "title": "BSC Mainnet / Reserve",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_block_number_diff{dns_hostname=\"hv_raw_bsc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_local_block_number{dns_hostname=\"hv_raw_bsc_mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_remote_block_number{dns_hostname=\"hv_raw_bsc_mainnet\"}"
    }
   ]
  },
  { "title": "|", "type": "text", "gridPos": { "h": 3, "w": 1, "x": 9, "y": 5 }, "options": { "content": "\n" } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_block_number_diff{dns_hostname=\"hv-raw3-bsc-mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_local_block_number{dns_hostname=\"hv-raw3-bsc-mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_bsc_mainnet_remote_block_number{dns_hostname=\"hv-raw3-bsc-mainnet\"}"
    }
   ]
  },
  { "title": "ETH Mainnet / Reserve", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_block_number_diff{dns_hostname=\"hv_raw_eth_mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_local_block_number{dns_hostname=\"hv_raw_eth_mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_remote_block_number{dns_hostname=\"hv_raw_eth_mainnet\"}"
    }
   ]
  },
  { "title": "|", "type": "text", "gridPos": { "h": 3, "w": 1, "x": 9, "y": 9 }, "options": { "content": "\n" } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_block_number_diff{dns_hostname=\"hv_raw3_eth_mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_local_block_number{dns_hostname=\"hv_raw3_eth_mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_eth_mainnet_remote_block_number{dns_hostname=\"hv_raw3_eth_mainnet\"}"
    }
   ]
  },
  { "title": "TRX Mainnet / Reserve", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_block_number_diff{dns_hostname=\"hv_raw_tron\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_local_block_number{dns_hostname=\"hv_raw_tron\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_remote_block_number{dns_hostname=\"hv_raw_tron\"}"
    }
   ]
  },
  { "title": "|", "type": "text", "gridPos": { "h": 3, "w": 1, "x": 9, "y": 13 }, "options": { "content": "\n" } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_block_number_diff{dns_hostname=\"hv-raw3-trx-node-mainnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_local_block_number{dns_hostname=\"hv-raw3-trx-node-mainnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockchain_trx_solidity_mainnet_remote_block_number{dns_hostname=\"hv-raw3-trx-node-mainnet\"}"
    }
   ]
  },
  { "title": "Kusama Main / Reserve", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv_raw2_kusama_validator\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv_raw2_kusama_validator\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv_raw2_kusama_validator\"}"
    }
   ]
  },
  { "title": "|", "type": "text", "gridPos": { "h": 3, "w": 1, "x": 9, "y": 17 }, "options": { "content": "\n" } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv-raw3-kusama\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv-raw3-kusama\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv-raw3-kusama\"}"
    }
   ]
  },
  { "title": "ETH testnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv_raw_eth_testnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv_raw_eth_testnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv_raw_eth_testnet\"}"
    }
   ]
  },
  { "title": "BSC testnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv_raw_bsc_testnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv_raw_bsc_testnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv_raw_bsc_testnet\"}"
    }
   ]
  },
  { "title": "BTC testnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv_raw_btc_testnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv_raw_btc_testnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv_raw_btc_testnet\"}"
    }
   ]
  },
  { "title": "TRX testnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Head Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_block_number_diff{dns_hostname=\"hv_raw_trx_testnet\"}"
    }
   ]
  },
  {
   "title": "Local Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_local_block_number{dns_hostname=\"hv_raw_trx_testnet\"}"
    }
   ]
  },
  {
   "title": "Remote Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Blockchain_remote_block_number{dns_hostname=\"hv_raw_trx_testnet\"}"
    }
   ]
  }
 ]
}