{
 "title": "Grafana metrics",
 "description": "Metrics about Grafana",
 "tags": [
  "grafana",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VICTORIAMETRICS", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(up{job=\"grafana\"}, dns_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{dns_hostname=\"$hostname\",job=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_dashboard{dns_hostname=\"$hostname\"}",
     "legendFormat": "{{dns_hostname}}"
    }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{dns_hostname=\"$hostname\"}",
     "legendFormat": "{{dns_hostname}}"
    }
   ]
  },
  {
   "title": "Playlist count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_playlists{dns_hostname=\"$hostname\"}",
     "legendFormat": "{{dns_hostname}}"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_build_info{dns_hostname=\"$hostname\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "http status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (irate(grafana_api_response_status_total{dns_hostname=\"$hostname\",job='grafana'}[5m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total{dns_hostname=\"$hostname\"}[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total{dns_hostname=\"$hostname\"}[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total{dns_hostname=\"$hostname\"}[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Most used handlers",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(topk(8, sum by (handler) (grafana_http_request_duration_seconds_bucket{dns_hostname=\"$hostname\",job=\"grafana\"})))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Grafana active alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(grafana_alerting_active_alerts{dns_hostname=\"$hostname\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Prometheus alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ALERTS)", "legendFormat": "firing alerts" }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{dns_hostname=\"$hostname\",job=\"grafana\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{dns_hostname=\"$hostname\",job=\"grafana\"})",
     "legendFormat": "memory usage"
    }
   ]
  }
 ]
}