{
 "title": "Haproxy Common Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dns_hostname",
    "label": "dns_hostname",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total ,dns_hostname)"
    }
   },
   {
    "name": "backend",
    "label": "backend",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total{dns_hostname=~\"$dns_hostname\"} ,proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "frontend",
    "query": {
     "query": "label_values(haproxy_frontend_sessions_total{dns_hostname=~\"$dns_hostname\"} ,proxy)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"} ,server)"
    }
   },
   { "name": "DS_VICTORIAMETRICS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Frontend Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Rate Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_sessions_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Rate Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_sessions_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status servers of backend",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"$server\", state=\"UP\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current sessions by servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"$server\"} ",
     "legendFormat": "Server1"
    }
   ]
  },
  {
   "title": "Current HTTP code responses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"1xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "1xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"2xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"3xx\"}) / sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"4xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"5xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "HTTP code responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})) by (code)/sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% good responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"1xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100) + (sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"2xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100) + (sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"3xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Responses Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"}))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "% 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"5xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=~\"5xx\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}