{
 "title": "Nalitek Haproxy Balancer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "dns_hostname",
    "label": "dns_hostname",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total ,dns_hostname)"
    }
   },
   {
    "name": "backend",
    "label": "backend",
    "query": {
     "query": "label_values(haproxy_backend_sessions_total{dns_hostname=~\"$dns_hostname\"} ,proxy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current HTTP code responses",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"1xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "1xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"2xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"3xx\"}) / sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "3xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"4xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"5xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "HTTP code responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})) by (code)/sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% good responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"1xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100) + (sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"2xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100) + (sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"3xx\"}))/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend internal total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "haproxy_backend_internal_errors_total{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=\"5xx\"})/ sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\", code=~\"5xx\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status servers of backend",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server1\", state=\"UP\"}) or min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_01\", state=\"UP\"})",
     "legendFormat": "Server1"
    },
    {
     "expr": "min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server2\", state=\"UP\"}) or min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_02\", state=\"UP\"})",
     "legendFormat": "Server2"
    },
    {
     "expr": "min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server3\", state=\"UP\"}) or min (haproxy_server_status{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_03\", state=\"UP\"})",
     "legendFormat": "Server3"
    }
   ]
  },
  {
   "title": "Current connections by servers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_used_connections_current{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\", server=\"Server1\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "haproxy_server_used_connections_current{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\", server=\"Server2\"}",
     "legendFormat": "Server2"
    },
    {
     "expr": "haproxy_server_used_connections_current{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\", server=\"Server3\"}",
     "legendFormat": "Server3"
    }
   ]
  },
  {
   "title": "Current sessions by servers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server1\"} or haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_01\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server2\"} or haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_02\"}",
     "legendFormat": "Server2"
    },
    {
     "expr": "haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"Server3\"} or haproxy_server_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\",server=\"db_03\"}",
     "legendFormat": "Server3"
    }
   ]
  },
  {
   "title": "Average time backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "haproxy_backend_queue_time_average_seconds{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_backend_connect_time_average_seconds{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_backend_response_time_average_seconds{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_backend_total_time_average_seconds{dns_hostname=~\"$dns_hostname\", proxy=\"$backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Responses Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum (rate(haproxy_backend_http_responses_total{dns_hostname=~\"$dns_hostname\", proxy=~\"$backend\"}))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "haproxy process pool used bytes & haproxy process pool allocated bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "haproxy_process_pool_allocated_bytes{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_process_pool_used_bytes{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_process_max_memory_bytes{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "haproxy process bytes out rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "haproxy_process_bytes_out_rate{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process current connections & sessions rate & connections rate limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "haproxy_process_current_connection_rate{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_process_limit_connection_rate{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "haproxy_process_current_session_rate{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process current connections & max connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "haproxy_process_current_connections{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "process current connections of max (%)"
    },
    {
     "expr": "haproxy_process_max_connections{dns_hostname=~\"$dns_hostname\"}",
     "legendFormat": "process current connections (k)"
    }
   ]
  },
  {
   "title": "Frontend Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"main_common\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Rate Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_sessions_total{dns_hostname=~\"$dns_hostname\",proxy=~\"main_common\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Current Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Rate Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_sessions_total{dns_hostname=~\"$dns_hostname\",proxy=~\"$backend\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}