{
 "title": "Nginx Dashboard",
 "tags": [ "main" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "dns_hostname",
    "label": "dns_hostname",
    "query": {
     "query": "label_values(http_response_count_total, dns_hostname)"
    }
   },
   {
    "name": "project_name",
    "label": "project_name",
    "query": {
     "query": "label_values(http_response_count_total{dns_hostname=~\"$dns_hostname\"}, project_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_count_total{dns_hostname=\"$dns_hostname\", project_name=\"$project_name\",scrape_type=\"nginx_exporter\", status=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RP24H",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\", status=\"200\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\", status=~'2..'}[$__range])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\", status=~'3..'}[$__range])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\", status=~'4..'}[$__range])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\", status=~'5..'}[$__range])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (http_response_time_seconds_hist_bucket{dns_hostname=\"$dns_hostname\", scrape_type=\"nginx_exporter\", status=\"200\"})) * 1000",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (http_response_time_seconds_hist_bucket{dns_hostname=\"$dns_hostname\", scrape_type=\"nginx_exporter\", status=\"200\"})) * 1000",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (http_response_time_seconds_hist_bucket{dns_hostname=\"$dns_hostname\", scrape_type=\"nginx_exporter\", status=\"200\"})) * 1000",
     "legendFormat": "75th"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_response_count_total{dns_hostname=\"$dns_hostname\", scrape_type=\"nginx_exporter\",status=~'...'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "floor(sum(increase(http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\",status=~'2..'}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{scrape_type=\"nginx_exporter\",status=~'3..'}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{scrape_type=\"nginx_exporter\",status=~'4..'}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "floor(sum(increase(main_site_http_response_count_total{scrape_type=\"nginx_exporter\",status=~'5..'}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Destribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "floor(sum by (status) (increase(http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\",status=~'4..'}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Destribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "floor(sum by (status) (increase(http_response_count_total{dns_hostname=\"$dns_hostname\",scrape_type=\"nginx_exporter\",status=~'5..'}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_response_time_seconds_hist_bucket{scrape_type=\"nginx_exporter\",status='200'}[10m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_response_time_seconds_hist_bucket{scrape_type=\"nginx_exporter\",status='200'}[10m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_response_time_seconds_hist_bucket{scrape_type=\"nginx_exporter\",status='200'}[10m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(http_response_time_seconds_hist_bucket{scrape_type=\"nginx_exporter\",status='200'}[10m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_response_time_seconds_hist_bucket{scrape_type=\"nginx_exporter\",status='200'}[10m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}