{
 "title": "Traefik Dashboard",
 "tags": [ "main" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "dns_hostname",
    "label": "dns_hostname",
    "query": {
     "query": "label_values(traefik_config_reloads_total,dns_hostname)"
    }
   },
   { "name": "DS_VICTORIAMETRICS", "label": "DS_VICTORIAMETRICS", "query": "prometheus" },
   {
    "name": "domain",
    "label": "domain",
    "query": {
     "query": "query_result( count by (host) (    traefik_service_requests_total{dns_hostname=~\"$dns_hostname\"}  ))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=\"200\", host=~\"$domain\", dns_hostname=\"$dns_hostname\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=\"200\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~'2..'}[$__range])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~'3..'}[$__range])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~'4..'}[$__range])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~'5..'}[$__range])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"...\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Respond time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le, host, dns_hostname) (\n    rate(traefik_entrypoint_request_duration_seconds_bucket{\n      dns_hostname=\"$dns_hostname\"\n    }[$__rate_interval])\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Entrypoint -> service rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"...\"}[1m]))",
     "legendFormat": "Entrypoint"
    },
    {
     "expr": "sum(rate(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"...\"}[1m]))",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "traefik_open_connections{dns_hostname=\"$dns_hostname\",entrypoint=\"web\"}[$__range]",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  label_replace(vector(25), \"dns_hostname\", \"dev-s1\", \"\", \"\")\n  * on(dns_hostname)\n  label_replace(vector(1), \"dns_hostname\", \"${dns_hostname:raw}\", \"\", \"\")\n)\nor\n(\n  label_replace(vector(30), \"dns_hostname\", \"service-s1\", \"\", \"\")\n  * on(dns_hostname)\n  label_replace(vector(1), \"dns_hostname\", \"${dns_hostname:raw}\", \"\", \"\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per domain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (host) (rate(traefik_entrypoint_requests_total{dns_hostname=\"$dns_hostname\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"2..\"}[1m])))",
     "legendFormat": "2xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", code=~\"3..\"}[1m])))",
     "legendFormat": "3xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", code=~\"4..\"}[1m])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "floor(sum(increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", code=~\"5..\"}[1m])))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "4xx Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "floor(sum by (code) (increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"4..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "floor(sum by (code) (increase(traefik_service_requests_total{dns_hostname=\"$dns_hostname\", host=~\"$domain\", code=~\"5..\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(traefik_service_requests_total{dns_hostname=\"$dns_hostname\",code=~\"...\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}