{
 "title": "Versions OS / MySQL / Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VICTORIAMETRICS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "OS Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Os Versions",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "MySQL Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "MySQL Version",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "mysql_version_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Postgresql Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Postgresql Version",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    { "expr": "pg_static", "legendFormat": "__auto" }
   ]
  }
 ]
}